version: "3"
services:
  db:
    image: postgres:12.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resliv_travel
    ports:
      - "5433:5432"

  travel:
    image: andreygreat/tbot_travel
    ports:
      - "8083:8083"
    volumes:
      - ./dockerconfig/application.yml:/application.yml:ro