tboot:
  tBotUsername: resliv_travel_test_bot
  tBootToken: 1450732291:AAFwmPTIePDMEqBXCsHp97-aRrZJQ3KFLXg
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://docker.for.win.localhost:5433/resliv_travel
#    url: jdbc:postgresql://localhost:5433/resliv_travel
    username: postgres
    password: password
server:
  port: 8083
