tboot:
  tBotUsername: BotUsername
  tBootToken: BootToke
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://docker.for.win.localhost:5433/resliv_travel
#    url: jdbc:postgresql://localhost:5433/resliv_travel
    username: postgres
    password: password
server:
  port: 8083
