tboot:
  tBotUsername: resliv_travel_test_bot
  tBootToken: 1450732291:AAFwmPTIePDMEqBXCsHp97-aRrZJQ3KFLXg
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/resliv_travel
    username: postgres
    password: password
  jpa:
    show-sql: true
server:
  port: 8083
